Seegya/feature/add comment table
WellyKorgis/project-blind-api pull request #31
Opened 2022-04-24 05:06 UTC by seegya

# :page_with_curl: What is this PR?
> I have added comment domain and its repository.

# :dart: Associated ticket
> #27

# :computer: How to test
>

`./gradlew build`
`docker-compose build`
`docker-compose up -d`
Go to docker shell and find a table in db using psql
`docker exec -it docker_container_name /bin/bash`
`psql -U postgres -W`
`\c blind-db`
`\dt`
`\d comment`

# :camera: Screenshot
>![image](https://user-images.githubusercontent.com/77556070/164957500-d6d6b61c-0244-45c6-a0f2-884a7e4a3007.png)

# :pencil2: Notes

2022-04-24 06:40 UTC, nmsohn reviewed
지금 3개 PR에 change들이 겹쳐 있어서 한 PR이 한 가지를 책임한다는 규칙과 어긋나는 것 같습니다. 다음에는 PR마다 develop 브랜치에서 새로운 브랜치를 생성해서 겹치는 부분 없이 만들면 좋겠습니다.

예를 들어, comment 관련 PR이면 comment 관련한 change만 commit 할 것

2022-04-24 06:40 UTC, nmsohn commented on src/main/java/com/blind/api/comment/domain/Comment.java
> +@Table(name = "comments")
DB 테이블은 복수형이 아닌 단수형으로 쓰는 것을 선호합니다

2022-04-24 06:55 UTC, nmsohn requested changes

2022-04-24 06:55 UTC, nmsohn commented on src/main/java/com/blind/api/controller/PostController.java
> +package com.blind.api.controller;public class PostController {
PR과 관련없는 change가 들어간 것 같습니다

2022-04-25 00:32 UTC, seegya commented on src/main/java/com/blind/api/controller/PostController.java
> +package com.blind.api.controller;public class PostController {
미쳣네요..

2022-04-25 00:35 UTC, seegya commented on src/main/java/com/blind/api/comment/domain/Comment.java
> +@Table(name = "comments")
넵 주의하겠습니다 ㅠ

2022-04-30 08:11 UTC, closed without merging