Seegya/feature/add post category
WellyKorgis/project-blind-api pull request #33
Opened 2022-04-24 05:24 UTC by seegya

# :page_with_curl: What is this PR?
> I have added post category, its repository and edited field name for user id as it was not descriptive enough.

# :dart: Associated ticket
> #24 

# :computer: How to test
> `./gradlew build`
`docker-compose build`
`docker-compose up -d`
Go to docker shell and find a table in db using psql
`docker exec -it docker_container_name /bin/bash`
`psql -U postgres -W`
`\c blind-db`
`\dt`
`\d post category`

# :camera: Screenshot
>![image](https://user-images.githubusercontent.com/77556070/164957911-2a6f13e7-ae75-4601-aec6-c953a0c2d0a6.png)

# :pencil2: Notes

2022-04-24 06:33 UTC, nmsohn requested changes

2022-04-24 06:33 UTC, nmsohn commented on src/main/java/com/blind/api/bookmark/domain/Bookmark.java
> +    private User userID;
타입이 User이기 때문에 필드명을 user 라고 하는 것을 제안합니다

2022-04-24 06:33 UTC, nmsohn commented on src/main/java/com/blind/api/post/domain/PostCategory.java
> +@Table(name = "post_category")
테이블명은 optional이기 때문에 CamelCase로 테이블명을 써주면 자동으로 post_category라고 명명된다고 합니다. https://stackoverflow.com/questions/56454871/why-table-annotation-is-optional-in-crud-operation-through-spring

2022-04-24 06:33 UTC, nmsohn commented on src/main/java/com/blind/api/bookmark/domain/Bookmark.java
> +@Table(name = "bookmarks")
DB 테이블은 복수형이 아닌 단수형으로 써주면 좋습니다. user 테이블 같은 경우 postgresql 예약어 중에 user가 있어 테이블 생성이 되지 않아 예외적으로 users라고 해주었습니다 (user의 다른 대안 이름이 있다면 알려주세요)

2022-04-24 06:33 UTC, nmsohn commented on src/main/java/com/blind/api/post/domain/Post.java
> +    private User userId;
타입이 User이기 때문에 필드명을 user 라고 하는 것을 제안합니다

2022-04-24 07:58 UTC, seegya commented on src/main/java/com/blind/api/bookmark/domain/Bookmark.java
> +@Table(name = "bookmarks")
넵넵 ㅎㅎ

2022-04-24 07:58 UTC, seegya commented on src/main/java/com/blind/api/post/domain/Post.java
> +    private User userId;
넵 조언 감사합니다

2022-04-25 00:44 UTC, seegya commented on src/main/java/com/blind/api/post/domain/PostCategory.java
> +@Table(name = "post_category")
넵 링크 참조해서 @Table 지웠어요! 감사합니다 👍

2022-04-30 08:11 UTC, closed without merging