Add book mark
WellyKorgis/project-blind-api pull request #40
Opened 2022-04-30 09:47 UTC by seegya

# :page_with_curl: What is this PR?
> Added a bookmark domain and repository. made sure the table name is singular

# :dart: Associated ticket
> #26 

# :computer: How to test
> `docker exec -it [container name] bash`
> `psql -U postgres`
> `dt`

# :camera: Screenshot
> 

# :pencil2: Notes

2022-04-30 21:19 UTC, nmsohn requested changes
이 PR에 https://github.com/WellyKorgis/project-blind-api/pull/41 에 있는 change가 다 포함되어 있어 위의 PR은 닫고 이거를 merge하는 걸로 해주세요!

2022-04-30 21:19 UTC, nmsohn commented on src/main/java/com/blind/api/post/domain/Post.java
> +@Table(name = "posts")
이거 하나 빼먹으신 것 같습니다 😁

2022-05-03 07:11 UTC, seegya commented on src/main/java/com/blind/api/post/domain/Post.java
> +@Table(name = "posts")
뭐야ㅠㅠㅠ reset hard로 히스토리 다 지우고 새로 했는데 쟤 왜 있는거죠...??????? ㅎ ㅏ...

2022-05-03 07:14 UTC, seegya commented
conflict 해결 했어용~~

2022-05-04 06:10 UTC, nmsohn commented on src/main/java/com/blind/api/post/domain/Post.java
> +@Table(name = "posts")
옛날 코드가 섞인 모양이네요ㅎㅎ 그리고 저 위에 @Table(name = "bookmark") 도 있어요

2022-05-04 07:24 UTC, seegya commented on src/main/java/com/blind/api/post/domain/Post.java
> +@Table(name = "posts")
북마크는 왜용...????

2022-05-04 23:08 UTC, nmsohn commented on src/main/java/com/blind/api/post/domain/Post.java
> +@Table(name = "posts")
@table 없어도 클래스명이 테이블명이 되는 거라 없어도 될 것 같아요. 사실 있어도 큰 지장은 없는데 한 줄이라도 코드를 줄이려고 하는 것이고 만약 PR 저자가 판단하기에 꼭 @table 이 필요한 것 같으면 댓글로 그 이유 남겨주시면 바로 approval 하겠습니다 :))))))

2022-05-04 23:09 UTC, nmsohn commented on src/main/java/com/blind/api/bookmark/domain/Bookmark.java
> +@Table(name = "bookmark")
이 annotation이 있어야 한다고 판단되면 알려주세요 :)

2022-05-04 23:19 UTC, nmsohn approved these changes
일단 미리 approve 할게요

2022-05-05 07:07 UTC, merged