Add company service to handle business logic
WellyKorgis/project-blind-api pull request #60
Opened 2022-05-20 10:27 UTC by nmsohn

# :page_with_curl: What is this PR?
This also adds GetCompanyResponse when fetching a company by id. CompanyService will handle getting a company data at this stage

# :dart: Associated ticket
#56 

# :computer: How to test
- Run `.\gradlew clean test`

# :pencil2: Notes

2022-05-24 06:11 UTC, nmsohn commented on docker-compose.yml
> +      context: .
context가 server로 바뀌어서 . 으로 다시 수정하였습니다

2022-05-24 06:17 UTC, nmsohn commented on src/main/java/com/blind/account/domain/Account.java
> -    @JoinColumn(name = "job_position_id", referencedColumnName = "id")
job history 기능을 위해 일단 job, company 관련 필드를 삭제하였습니다. 추후 디스커션을 통해 job history 엔티티를 추가할 예정입니다

2022-05-24 06:17 UTC, nmsohn commented on src/main/java/com/blind/company/api/controller/CompanyController.java
> +        if(getCompanyResponse != null) return ResponseEntity.status(HttpStatus.OK).body(getCompanyResponse);
추후 Response를 깔끔하게 핸들링할 수 있게 리팩토링이 필요합니다

2022-05-24 06:17 UTC, nmsohn commented on src/main/java/com/blind/company/api/dto/response/CompanyCategoryResponse.java
> +public class CompanyCategoryResponse extends BaseDtoResponse {
SoC를 위해 DTO를 추가했습니다

2022-05-24 06:17 UTC, nmsohn commented on src/main/java/com/blind/company/api/service/CompanyServiceImpl.java
> +public class CompanyServiceImpl implements CompanyService {
서비스단을 추가해 프레젠테이션 레이어와 비즈니스 로직을 분리했습니다

2022-05-24 06:17 UTC, nmsohn commented on src/test/java/com/blind/api/controller/CompanyControllerTests.java
> +public class CompanyControllerTests {
유닛 테스트로 reusable하게 리팩토링이 필요합니다

2022-05-24 07:25 UTC, seegya commented on src/main/java/com/blind/account/domain/Account.java
> -    @JoinColumn(name = "job_position_id", referencedColumnName = "id")
넵!

2022-05-24 09:11 UTC, seegya requested changes
api endpoint 수정 부탁드립니다~~~

2022-05-24 09:11 UTC, seegya commented on src/test/java/com/blind/api/controller/CompanyControllerTests.java
> +public class CompanyControllerTests {
이거 잘 이해 안가는데 다음 회의때 설명 해 주실 수 있으신가요??

2022-05-24 09:11 UTC, seegya commented on src/main/java/com/blind/company/api/service/CompanyServiceImpl.java
> +public class CompanyServiceImpl implements CompanyService {
crud 이외에 다른 비즈니스 로직 구상하고 계신게 있으신가요? 아니면 데이터 액세스를 위해서 서비스 레이어를 추가하시는건가용?

2022-05-24 09:39 UTC, nmsohn commented on src/main/java/com/blind/company/api/controller/CompanyController.java
> +        if(getCompanyResponse != null) return ResponseEntity.status(HttpStatus.OK).body(getCompanyResponse);
오 좋은 제안입니다. api 버저닝을 고려해서 api 대신 v1 을 넣는 건 어떨까요? Uri 디자인도 같이 이야기 나눠보면 좋겠어요

2022-05-24 10:50 UTC, nmsohn commented on src/main/java/com/blind/company/api/service/CompanyServiceImpl.java
> +public class CompanyServiceImpl implements CompanyService {
서비스 레이어는 데이터레이어와 표현 레이어 사이에서 파사드같은 역할을 합니다. 여러 아키텍처에서 쓰이는 국밥같은 패턴이에요. 여기서 트랜잭션 처리 외에도 엔티티를 dto에 맞게 매핑하거나 이벤트 처리하거나 유효성 검사같은 것을 할 수도 있습니다.

만약 단순 조회 기능만 있다면 굳이 서비스를 넣을 필요는 없고 바로 리포지토리로 접근해도 되긴 합니다. 관련내용은 mvc 나 ddd 아키텍처 찾아보면 많이 나올거에요.

답변이 잘 되었는지는 모르겠지만 생각해둔 아키텍처가 따로 있거나 궁금한 부분이 있다면 다음 회의 아젠다로 올려놓을게요😊

2022-05-24 10:59 UTC, nmsohn commented on src/test/java/com/blind/api/controller/CompanyControllerTests.java
> +public class CompanyControllerTests {
당연하죠. 깔끔한 코드는 아니라 가독성이 떨어지긴 하네요. 회의 때까지 좀 더 다듬어 보겠습니다

2022-05-24 11:04 UTC, nmsohn commented
> api endpoint 수정 부탁드립니다~~~

오 좋은 제안입니다. api 버저닝을 고려해서 api 대신 v1 을 넣는 건 어떨까요? 

그러고 보니 Uri 디자인을 디자인 단계에서 빼먹고 진행했네요. 다음 회의 때 더 의견 나눠보아요

2022-05-24 11:25 UTC, nmsohn commented on build.gradle
> +    implementation 'org.fluttercode.datafactory:datafactory:0.8'
안쓰이는 패키지는 지우도록 합시다

2022-05-25 08:48 UTC, seegya commented on src/main/java/com/blind/company/api/controller/CompanyController.java
> +        if(getCompanyResponse != null) return ResponseEntity.status(HttpStatus.OK).body(getCompanyResponse);
아 /api/v1/{domain}이러는게 오픈 api 버전관리를 위해서 있는거였네요?? 오늘도 배우고갑니다..

2022-05-25 08:51 UTC, seegya commented on src/main/java/com/blind/company/api/service/CompanyServiceImpl.java
> +public class CompanyServiceImpl implements CompanyService {
아하 그렇군요~~!! service와 serviceimpl 분리는 다음 회의때 의논해 보아요 저도 확장성에 대해 조사 조금 더 해오겠습니당

2022-05-25 08:51 UTC, seegya commented on src/test/java/com/blind/api/controller/CompanyControllerTests.java
> +public class CompanyControllerTests {
감자합니당

2022-05-25 08:53 UTC, seegya commented on build.gradle
> +    implementation 'org.fluttercode.datafactory:datafactory:0.8'
넵 추가로 인텔리제이에서 사용하지 않는 import 알아서 지우는 기능 발견했어요
[https://intellij-support.jetbrains.com/hc/en-us/community/posts/206915775-How-to-enable-remove-unused-imports-]
Preferences->Editor->Auto Import->Optimize Imports on the Fly will automatically remove unuxed imports.

2022-05-25 08:54 UTC, seegya commented on build.gradle
> +    implementation 'org.fluttercode.datafactory:datafactory:0.8'
넵 추가로 인텔리제이에서 사용하지 않는 import 알아서 지우는 기능 발견했어요
[https://intellij-support.jetbrains.com/hc/en-us/community/posts/206915775-How-to-enable-remove-unused-imports-](https://github.com/WellyKorgis/project-blind-api/pull/60/files/url)
Preferences->Editor->Auto Import->Optimize Imports on the Fly will automatically remove unuxed imports.

2022-05-25 23:32 UTC, nmsohn commented on build.gradle
> +    implementation 'org.fluttercode.datafactory:datafactory:0.8'
앗, 근데 저거는 저에게 남기는 코멘트였어요

2022-05-31 08:33 UTC, seegya reviewed
질문있어요~!~

2022-05-31 08:33 UTC, seegya commented on src/main/java/com/blind/company/api/controller/CompanyController.java
> +    public ResponseEntity<? extends BaseDtoResponse> getCompanyById(@PathVariable("id") UUID id)
🙆‍♀️

2022-05-31 08:33 UTC, seegya commented on src/main/java/com/blind/company/api/dto/response/CompanyResponse.java
>  @Builder
이거 setter 빼신이유가 굳이 dto는 setter 있을 필요없어서인거죠? dto 추가해보자고 의견 내주신 이후로 찾아봤는데 넘 흥미롭네여!! 회사에서도 못 배운걸 갠플에서 배웁니당ㅎ

2022-05-31 08:33 UTC, seegya commented on src/main/java/com/blind/company/domain/Company.java
> -@Setter
여기서는 entity 순수성을 위해서 setter를 제외하신건가요?? 
질문) 그러면 만약에 데이터가 POST 메소드로 들어오면 어떻게 setter가 없어도 저장되나요??

2022-05-31 08:33 UTC, seegya commented on src/main/java/com/blind/post/api/PostController.java
> -import java.util.*;
얘 되게 제너럴하게 되어있었네요ㅎㅎ....

2022-05-31 08:33 UTC, seegya commented on src/main/java/com/blind/shared/api/BaseDtoResponse.java
> +@Getter
굿굿

2022-05-31 08:35 UTC, seegya approved these changes
approve

2022-05-31 09:31 UTC, nmsohn commented on src/main/java/com/blind/company/domain/Company.java
> -@Setter
현 PR에서 쓰이지 않기도 하고 company 객체의 경우 유저가 아니라 자체 데이터베이스를 구축해서 쓰지 않나 싶어 일단 불변 객체로 생각하고 있습니다. 

아직 더 공부를 해봐야 하겠지만 개인적으로 setter 보다는 생성자나 빌더 쓰는 게 가독성면에서나 유지보수에도 좋다고 봐요. POST는 setter가 없어도 위와 같은 방법으로 transaction 가능해요

OOP관점이랑 data 관점에서 getter, setter 를 왜 쓰는지/또는 왜 안쓰는지는 스택오버플로우나 국내 커뮤니티에서도 토론 엄청 많은데 한가지 정답이 있다기 보단 케바케라 보는 게 좋을 것 같아요 😂😂

2022-06-05 01:23 UTC, seegya commented on src/main/java/com/blind/company/api/dto/response/CompanyResponse.java
>  @Builder
아하 그냥 transfer 만 목적이기 때문에 immutable 해야 하군여

2022-06-05 01:25 UTC, seegya commented on src/main/java/com/blind/company/domain/Company.java
> -@Setter
아아아 빌더를 쓰는거군요! 다른 방법도 배워보는 기회가 될 것 같아 좋습니당👍

2022-06-06 22:17 UTC, merged